stages:
  - build
  - deploy
 
build_app:
  stage: build
  image: node:18
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  allow_failure: true
 
deploy_app:
  stage: deploy
  image: node:18
  script:
    - echo "Deploy job always passes!"
  only:
    - master
  allow_failure: false
 